# coding: utf-8

"""
    WEMDE Dispatch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wemde_dispatch_client.models.dispatch_instructions_history_filter import DispatchInstructionsHistoryFilter

class TestDispatchInstructionsHistoryFilter(unittest.TestCase):
    """DispatchInstructionsHistoryFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DispatchInstructionsHistoryFilter:
        """Test DispatchInstructionsHistoryFilter
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DispatchInstructionsHistoryFilter`
        """
        model = DispatchInstructionsHistoryFilter()
        if include_optional:
            return DispatchInstructionsHistoryFilter(
                search_all = True,
                facility_id = '',
                from_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                to_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return DispatchInstructionsHistoryFilter(
        )
        """

    def testDispatchInstructionsHistoryFilter(self):
        """Test DispatchInstructionsHistoryFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
