# coding: utf-8

"""
    WEMDE Dispatch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wemde_dispatch_client.models.rcm_datum import RcmDatum

class TestRcmDatum(unittest.TestCase):
    """RcmDatum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RcmDatum:
        """Test RcmDatum
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RcmDatum`
        """
        model = RcmDatum()
        if include_optional:
            return RcmDatum(
                facility_code = '',
                rcoq = 1.337
            )
        else:
            return RcmDatum(
                facility_code = '',
                rcoq = 1.337,
        )
        """

    def testRcmDatum(self):
        """Test RcmDatum"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
