# coding: utf-8

"""
    WEMDE Dispatch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wemde_dispatch_client.api.not_in_service_capacity_api import NotInServiceCapacityApi


class TestNotInServiceCapacityApi(unittest.TestCase):
    """NotInServiceCapacityApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotInServiceCapacityApi()

    def tearDown(self) -> None:
        pass

    def test_get_quantities(self) -> None:
        """Test case for get_quantities

        /quantities - GET
        """
        pass


if __name__ == '__main__':
    unittest.main()
