# coding: utf-8

"""
    WEMDE Dispatch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wemde_dispatch_client.models.trapezium_adjustment import TrapeziumAdjustment

class TestTrapeziumAdjustment(unittest.TestCase):
    """TrapeziumAdjustment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrapeziumAdjustment:
        """Test TrapeziumAdjustment
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrapeziumAdjustment`
        """
        model = TrapeziumAdjustment()
        if include_optional:
            return TrapeziumAdjustment(
                market_service = '',
                trapezium_adjustment_details = [
                    wemde_dispatch_client.models.trapezium_adjustment_detail.TrapeziumAdjustmentDetail(
                        facility_code = '', 
                        enablement_minimum_value_used = 1.337, 
                        low_breakpoint_value_used = 1.337, 
                        high_breakpoint_value_used = 1.337, 
                        enablement_maximum_value_used = 1.337, 
                        downwards_ramp_rate_value_used = 1.337, 
                        upwards_ramp_rate_value_used = 1.337, )
                    ]
            )
        else:
            return TrapeziumAdjustment(
        )
        """

    def testTrapeziumAdjustment(self):
        """Test TrapeziumAdjustment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
