# coding: utf-8

"""
    WEMDE Dispatch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wemde_dispatch_client.models.facility_schedule_detail import FacilityScheduleDetail

class TestFacilityScheduleDetail(unittest.TestCase):
    """FacilityScheduleDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FacilityScheduleDetail:
        """Test FacilityScheduleDetail
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FacilityScheduleDetail`
        """
        model = FacilityScheduleDetail()
        if include_optional:
            return FacilityScheduleDetail(
                facility_code = '',
                contingency_raise_pf = 1.337,
                contingency_lower_pf = 1.337,
                regulation_raise_pf = 1.337,
                regulation_lower_pf = 1.337,
                rocof_pf = 1.337,
                dispatch_binding_flag = True,
                contingency = 1.337,
                initial_mw = 1.337,
                fast_start_flag = True,
                fast_start_initial_mode_time = 56,
                fast_start_initial_mode = 56,
                what_if_initial_mw = 1.337,
                fast_start_target_mode = 56,
                fast_start_target_mode_time = 56,
                estimated_fcess_uplift_payment = 1.337,
                nol_demand = 1.337,
                congestion_rental = 1.337,
                facility_risk = 1.337
            )
        else:
            return FacilityScheduleDetail(
        )
        """

    def testFacilityScheduleDetail(self):
        """Test FacilityScheduleDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
