# coding: utf-8

"""
    WEMDE Dispatch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wemde_dispatch_client.models.trapezium_adjustment_detail import TrapeziumAdjustmentDetail

class TestTrapeziumAdjustmentDetail(unittest.TestCase):
    """TrapeziumAdjustmentDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrapeziumAdjustmentDetail:
        """Test TrapeziumAdjustmentDetail
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrapeziumAdjustmentDetail`
        """
        model = TrapeziumAdjustmentDetail()
        if include_optional:
            return TrapeziumAdjustmentDetail(
                facility_code = '',
                enablement_minimum_value_used = 1.337,
                low_breakpoint_value_used = 1.337,
                high_breakpoint_value_used = 1.337,
                enablement_maximum_value_used = 1.337,
                downwards_ramp_rate_value_used = 1.337,
                upwards_ramp_rate_value_used = 1.337
            )
        else:
            return TrapeziumAdjustmentDetail(
        )
        """

    def testTrapeziumAdjustmentDetail(self):
        """Test TrapeziumAdjustmentDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
