# coding: utf-8

"""
    WEMDE Dispatch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wemde_dispatch_client.api.reference_trading_price_api import ReferenceTradingPriceApi


class TestReferenceTradingPriceApi(unittest.TestCase):
    """ReferenceTradingPriceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReferenceTradingPriceApi()

    def tearDown(self) -> None:
        pass

    def test_get_referencetradingprices(self) -> None:
        """Test case for get_referencetradingprices

        /referenceTradingPrices - GET
        """
        pass


if __name__ == '__main__':
    unittest.main()
