# coding: utf-8

"""
    WEMDE Dispatch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wemde_dispatch_client.api.trading_day_report_api import TradingDayReportApi


class TestTradingDayReportApi(unittest.TestCase):
    """TradingDayReportApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TradingDayReportApi()

    def tearDown(self) -> None:
        pass

    def test_get_api_v1_tradingdayreport_tradingdayreport(self) -> None:
        """Test case for get_api_v1_tradingdayreport_tradingdayreport

        Retrieves the Trading Day Report
        """
        pass


if __name__ == '__main__':
    unittest.main()
