# coding: utf-8

"""
    WEMDE Dispatch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wemde_dispatch_client.models.fsip import Fsip

class TestFsip(unittest.TestCase):
    """Fsip unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Fsip:
        """Test Fsip
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Fsip`
        """
        model = Fsip()
        if include_optional:
            return Fsip(
                t1 = 1.337,
                t2 = 1.337,
                t3 = 1.337,
                t4 = 1.337,
                minimum_load = 1.337
            )
        else:
            return Fsip(
                t1 = 1.337,
                t2 = 1.337,
                t3 = 1.337,
                t4 = 1.337,
                minimum_load = 1.337,
        )
        """

    def testFsip(self):
        """Test Fsip"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
