# coding: utf-8

"""
    WEMDE Dispatch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wemde_dispatch_client.api.dsp_dispatch_instruction_api import DSPDispatchInstructionApi


class TestDSPDispatchInstructionApi(unittest.TestCase):
    """DSPDispatchInstructionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DSPDispatchInstructionApi()

    def tearDown(self) -> None:
        pass

    def test_get_dspdispatchinstructionparticipantwise(self) -> None:
        """Test case for get_dspdispatchinstructionparticipantwise

        Retrieves Participant wise DSP dispatch instruction for each participant
        """
        pass

    def test_get_dspdispatchinstructions(self) -> None:
        """Test case for get_dspdispatchinstructions

        Retrieves the DSP dispatch instruction for all participants
        """
        pass

    def test_get_predispatchdata(self) -> None:
        """Test case for get_predispatchdata

        Pre-Dispatch DSP Schedule information for the a specified interval (for Pre-Dispatch 2 days between start and end dates of the request)
        """
        pass

    def test_get_weekaheaddispatchdata(self) -> None:
        """Test case for get_weekaheaddispatchdata

        Week-Ahead Dispatch DSP Schedule information for the a specified interval (7 days between start and end dates for week ahead)
        """
        pass

    def test_put_dispatchinstructionack_dispatchinstructionid(self) -> None:
        """Test case for put_dispatchinstructionack_dispatchinstructionid

        Acknowledge the Dispatch Instruction
        """
        pass


if __name__ == '__main__':
    unittest.main()
