# coding: utf-8

"""
    WEMDE Dispatch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wemde_dispatch_client.models.left_hand_side import LeftHandSide

class TestLeftHandSide(unittest.TestCase):
    """LeftHandSide unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LeftHandSide:
        """Test LeftHandSide
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LeftHandSide`
        """
        model = LeftHandSide()
        if include_optional:
            return LeftHandSide(
                term = '',
                coefficient = 1.337,
                term_type = '',
                index = 56
            )
        else:
            return LeftHandSide(
        )
        """

    def testLeftHandSide(self):
        """Test LeftHandSide"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
