# coding: utf-8

"""
    WEMDE Dispatch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wemde_dispatch_client.models.dispatch_instruction_details_response import DispatchInstructionDetailsResponse

class TestDispatchInstructionDetailsResponse(unittest.TestCase):
    """DispatchInstructionDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DispatchInstructionDetailsResponse:
        """Test DispatchInstructionDetailsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DispatchInstructionDetailsResponse`
        """
        model = DispatchInstructionDetailsResponse()
        if include_optional:
            return DispatchInstructionDetailsResponse(
                dispatch_instruction_id = '',
                dispatch_interval = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                issued_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                data = [
                    wemde_dispatch_client.models.dispatch_instructions_data.DispatchInstructionsData(
                        facility_code = '', 
                        sent_out = wemde_dispatch_client.models.dispatch.Dispatch(
                            dispatch_target = 1.337, 
                            dispatch_cap = 1.337, ), 
                        as_generated = wemde_dispatch_client.models.dispatch.Dispatch(
                            dispatch_target = 1.337, 
                            dispatch_cap = 1.337, ), 
                        ramp_rate = 1.337, 
                        regulation_raise_enablement_quantity = 1.337, 
                        regulation_lower_enablement_quantity = 1.337, 
                        contingency_raise_enablement_quantity = 1.337, 
                        contingency_lower_enablement_quantity = 1.337, 
                        rocof_enablement_quantity = 1.337, )
                    ]
            )
        else:
            return DispatchInstructionDetailsResponse(
        )
        """

    def testDispatchInstructionDetailsResponse(self):
        """Test DispatchInstructionDetailsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
