# coding: utf-8

"""
    WEMDE Dispatch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wemde_dispatch_client.models.constraint import Constraint

class TestConstraint(unittest.TestCase):
    """Constraint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Constraint:
        """Test Constraint
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Constraint`
        """
        model = Constraint()
        if include_optional:
            return Constraint(
                id = '',
                description = '',
                left_hand_side_value = 1.337,
                operator = '',
                constraint_type = '',
                right_hand_side_value = 1.337,
                default_rhs = 1.337,
                binding_constraint_flag = True,
                near_binding_constraint_flag = True,
                shadow_price = 1.337,
                is_intervention_event = True,
                slack_variables = [
                    wemde_dispatch_client.models.slack_variable.SlackVariable(
                        variable = '', 
                        value = 1.337, )
                    ]
            )
        else:
            return Constraint(
        )
        """

    def testConstraint(self):
        """Test Constraint"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
