# coding: utf-8

"""
    WEMDE Dispatch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wemde_dispatch_client.models.facility_schedule import FacilitySchedule

class TestFacilitySchedule(unittest.TestCase):
    """FacilitySchedule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FacilitySchedule:
        """Test FacilitySchedule
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FacilitySchedule`
        """
        model = FacilitySchedule()
        if include_optional:
            return FacilitySchedule(
                facility_code = '',
                quantity = 1.337,
                ess_pre_processing_condition_flag = True
            )
        else:
            return FacilitySchedule(
        )
        """

    def testFacilitySchedule(self):
        """Test FacilitySchedule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
