# coding: utf-8

"""
    WEMDE Dispatch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wemde_dispatch_client.api.dispatch_case_api import DispatchCaseApi


class TestDispatchCaseApi(unittest.TestCase):
    """DispatchCaseApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DispatchCaseApi()

    def tearDown(self) -> None:
        pass

    def test_get_api_v1_dispatchcase_dispatchdata(self) -> None:
        """Test case for get_api_v1_dispatchcase_dispatchdata

        Retrieves the Case Data for Dispatch Run
        """
        pass

    def test_get_api_v1_dispatchcase_dispatchdataoutcomes(self) -> None:
        """Test case for get_api_v1_dispatchcase_dispatchdataoutcomes

        Retrieves Case Data from the Central Dispatch Process through a range of past Primary Dispatch Intervals
        """
        pass

    def test_get_api_v1_dispatchcase_predispatchdata(self) -> None:
        """Test case for get_api_v1_dispatchcase_predispatchdata

        Retrieves Case Data from the Central Dispatch Process through a range of past Primary Dispatch Intervals
        """
        pass

    def test_get_api_v1_dispatchcase_weekaheaddispatchdata(self) -> None:
        """Test case for get_api_v1_dispatchcase_weekaheaddispatchdata

        Retrieves the Case Data for Week Ahead Dispatch Run
        """
        pass


if __name__ == '__main__':
    unittest.main()
