# coding: utf-8

"""
    WEMDE Dispatch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wemde_dispatch_client.models.network_risk import NetworkRisk

class TestNetworkRisk(unittest.TestCase):
    """NetworkRisk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NetworkRisk:
        """Test NetworkRisk
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NetworkRisk`
        """
        model = NetworkRisk()
        if include_optional:
            return NetworkRisk(
                network_contingency = '',
                network_risk_value = 1.337,
                associated_facility_codes = [
                    ''
                    ]
            )
        else:
            return NetworkRisk(
        )
        """

    def testNetworkRisk(self):
        """Test NetworkRisk"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
