# coding: utf-8

"""
    WEMDE Dispatch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wemde_dispatch_client.models.facility_standing_data import FacilityStandingData

class TestFacilityStandingData(unittest.TestCase):
    """FacilityStandingData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FacilityStandingData:
        """Test FacilityStandingData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FacilityStandingData`
        """
        model = FacilityStandingData()
        if include_optional:
            return FacilityStandingData(
                facility_registration_status = '',
                facility_class = '',
                storage_constraints = True,
                inertia = 1.337,
                tau_factor = 1.337,
                unconstrained_forecast_source = 'scada',
                effective_dispatch_interval_from = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return FacilityStandingData(
                facility_registration_status = '',
                facility_class = '',
                storage_constraints = True,
                inertia = 1.337,
                tau_factor = 1.337,
                unconstrained_forecast_source = 'scada',
                effective_dispatch_interval_from = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testFacilityStandingData(self):
        """Test FacilityStandingData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
