# coding: utf-8

"""
    WEMDE Dispatch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wemde_dispatch_client.models.swagger_reference_trading_prices_root import SwaggerReferenceTradingPricesRoot

class TestSwaggerReferenceTradingPricesRoot(unittest.TestCase):
    """SwaggerReferenceTradingPricesRoot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SwaggerReferenceTradingPricesRoot:
        """Test SwaggerReferenceTradingPricesRoot
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SwaggerReferenceTradingPricesRoot`
        """
        model = SwaggerReferenceTradingPricesRoot()
        if include_optional:
            return SwaggerReferenceTradingPricesRoot(
                data = wemde_dispatch_client.models.swagger_reference_trading_prices.SwaggerReferenceTradingPrices(
                    trading_day = '', 
                    reference_trading_prices = [
                        wemde_dispatch_client.models.reference_trading_prices.ReferenceTradingPrices(
                            trading_interval = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            reference_trading_price = 1.337, 
                            is_published = True, )
                        ], ),
                transaction_id = ''
            )
        else:
            return SwaggerReferenceTradingPricesRoot(
        )
        """

    def testSwaggerReferenceTradingPricesRoot(self):
        """Test SwaggerReferenceTradingPricesRoot"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
