# coding: utf-8

"""
    WEMDE Dispatch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wemde_dispatch_client.models.congestion_rental_calculation import CongestionRentalCalculation

class TestCongestionRentalCalculation(unittest.TestCase):
    """CongestionRentalCalculation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CongestionRentalCalculation:
        """Test CongestionRentalCalculation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CongestionRentalCalculation`
        """
        model = CongestionRentalCalculation()
        if include_optional:
            return CongestionRentalCalculation(
                dispatch_interval = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                congestion_rentals = [
                    wemde_dispatch_client.models.congestion_rental.CongestionRental(
                        facility_code = '', 
                        congestion_rental_value = 1.337, )
                    ]
            )
        else:
            return CongestionRentalCalculation(
        )
        """

    def testCongestionRentalCalculation(self):
        """Test CongestionRentalCalculation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
