# coding: utf-8

"""
    WEMDE Dispatch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wemde_dispatch_client.models.dsp_reduction_instruction import DspReductionInstruction

class TestDspReductionInstruction(unittest.TestCase):
    """DspReductionInstruction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DspReductionInstruction:
        """Test DspReductionInstruction
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DspReductionInstruction`
        """
        model = DspReductionInstruction()
        if include_optional:
            return DspReductionInstruction(
                trading_interval = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                requested_reductions = [
                    wemde_dispatch_client.models.requested_reduction.RequestedReduction(
                        facility_code = '', 
                        requested_reduction_value = 56, )
                    ]
            )
        else:
            return DspReductionInstruction(
        )
        """

    def testDspReductionInstruction(self):
        """Test DspReductionInstruction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
