# coding: utf-8

"""
    WEMDE Dispatch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from wemde_dispatch_client.models.swagger_dispatch_data_outcomes_solution_datum import SwaggerDispatchDataOutcomesSolutionDatum
from typing import Optional, Set
from typing_extensions import Self

class DispatchDataOutcomesData(BaseModel):
    """
    DispatchDataOutcomesData
    """ # noqa: E501
    dispatch_data_issue_id: Optional[StrictStr] = Field(default=None, alias="dispatchDataIssueID")
    solution_data: Optional[List[SwaggerDispatchDataOutcomesSolutionDatum]] = Field(default=None, alias="solutionData")
    __properties: ClassVar[List[str]] = ["dispatchDataIssueID", "solutionData"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DispatchDataOutcomesData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in solution_data (list)
        _items = []
        if self.solution_data:
            for _item in self.solution_data:
                if _item:
                    _items.append(_item.to_dict())
            _dict['solutionData'] = _items
        # set to None if dispatch_data_issue_id (nullable) is None
        # and model_fields_set contains the field
        if self.dispatch_data_issue_id is None and "dispatch_data_issue_id" in self.model_fields_set:
            _dict['dispatchDataIssueID'] = None

        # set to None if solution_data (nullable) is None
        # and model_fields_set contains the field
        if self.solution_data is None and "solution_data" in self.model_fields_set:
            _dict['solutionData'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DispatchDataOutcomesData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dispatchDataIssueID": obj.get("dispatchDataIssueID"),
            "solutionData": [SwaggerDispatchDataOutcomesSolutionDatum.from_dict(_item) for _item in obj["solutionData"]] if obj.get("solutionData") is not None else None
        })
        return _obj


