# coding: utf-8

"""
    WEMDE Dispatch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class FacilityLossFactor(BaseModel):
    """
    An array of Facility Loss Factors.
    """ # noqa: E501
    facility_code: StrictStr = Field(description="The Facility that the Facility Loss Factor refers to.", alias="facilityCode")
    transmission_loss_factor: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The Transmission Loss Factor of the Facility. This has a default value of 1 if no Transmission Loss Factor is available for the Facility.", alias="transmissionLossFactor")
    distribution_loss_factor: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The Distribution Loss Factor of the Facility. This has a default value of 1 if no Distribution Loss Factor is available for the Facility.", alias="distributionLossFactor")
    __properties: ClassVar[List[str]] = ["facilityCode", "transmissionLossFactor", "distributionLossFactor"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FacilityLossFactor from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FacilityLossFactor from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "facilityCode": obj.get("facilityCode"),
            "transmissionLossFactor": obj.get("transmissionLossFactor"),
            "distributionLossFactor": obj.get("distributionLossFactor")
        })
        return _obj


