# coding: utf-8

"""
    WEMDE Dispatch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self

class Fsip(BaseModel):
    """
    Fsip
    """ # noqa: E501
    t1: Union[StrictFloat, StrictInt] = Field(description="The time it takes for the Facility to synchronise after receiving dispatch instruction.")
    t2: Union[StrictFloat, StrictInt] = Field(description="The time it takes for the Facility to reach minimum loading.")
    t3: Union[StrictFloat, StrictInt] = Field(description="The time required for the Facility to operate at or beyond the minimum loading.")
    t4: Union[StrictFloat, StrictInt] = Field(description="The time required for the Facility to shut down from minimum loading.")
    minimum_load: Union[StrictFloat, StrictInt] = Field(description="The quantity (in MW) of Injection or Withdrawal that the Facility must be operated at or beyond during the period t3.", alias="minimumLoad")
    __properties: ClassVar[List[str]] = ["t1", "t2", "t3", "t4", "minimumLoad"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Fsip from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Fsip from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "t1": obj.get("t1"),
            "t2": obj.get("t2"),
            "t3": obj.get("t3"),
            "t4": obj.get("t4"),
            "minimumLoad": obj.get("minimumLoad")
        })
        return _obj


