# coding: utf-8

"""
    WEMDE Dispatch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class SwaggerTradingDayReportFacility(BaseModel):
    """
    SwaggerTradingDayReportFacility
    """ # noqa: E501
    facility_code: Optional[StrictStr] = Field(default=None, alias="facilityCode")
    energy_uplift_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="energyUpliftPrice")
    uplift_mispricing_trigger: Optional[StrictInt] = Field(default=None, alias="upliftMispricingTrigger")
    __properties: ClassVar[List[str]] = ["facilityCode", "energyUpliftPrice", "upliftMispricingTrigger"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SwaggerTradingDayReportFacility from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if facility_code (nullable) is None
        # and model_fields_set contains the field
        if self.facility_code is None and "facility_code" in self.model_fields_set:
            _dict['facilityCode'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SwaggerTradingDayReportFacility from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "facilityCode": obj.get("facilityCode"),
            "energyUpliftPrice": obj.get("energyUpliftPrice"),
            "upliftMispricingTrigger": obj.get("upliftMispricingTrigger")
        })
        return _obj


