# coding: utf-8

"""
    WEMDE Dispatch

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from wemde_dispatch_client.models.trapezium_adjustment_detail import TrapeziumAdjustmentDetail
from typing import Optional, Set
from typing_extensions import Self

class TrapeziumAdjustment(BaseModel):
    """
    TrapeziumAdjustment
    """ # noqa: E501
    market_service: Optional[StrictStr] = Field(default=None, description="Market Service for which the Trapezium Adjustments in a Semi-Scheduled Facility applies to", alias="marketService")
    trapezium_adjustment_details: Optional[List[TrapeziumAdjustmentDetail]] = Field(default=None, description="An array of Trapezium Adjustment Details that determines the final value of Enablement Minimum, Enablement Maximum, Low Breakpoint, High Breakpoint, and Ramp-Rates used in a relevant Market Service for each Facility", alias="trapeziumAdjustmentDetails")
    __properties: ClassVar[List[str]] = ["marketService", "trapeziumAdjustmentDetails"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TrapeziumAdjustment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in trapezium_adjustment_details (list)
        _items = []
        if self.trapezium_adjustment_details:
            for _item in self.trapezium_adjustment_details:
                if _item:
                    _items.append(_item.to_dict())
            _dict['trapeziumAdjustmentDetails'] = _items
        # set to None if market_service (nullable) is None
        # and model_fields_set contains the field
        if self.market_service is None and "market_service" in self.model_fields_set:
            _dict['marketService'] = None

        # set to None if trapezium_adjustment_details (nullable) is None
        # and model_fields_set contains the field
        if self.trapezium_adjustment_details is None and "trapezium_adjustment_details" in self.model_fields_set:
            _dict['trapeziumAdjustmentDetails'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TrapeziumAdjustment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "marketService": obj.get("marketService"),
            "trapeziumAdjustmentDetails": [TrapeziumAdjustmentDetail.from_dict(_item) for _item in obj["trapeziumAdjustmentDetails"]] if obj.get("trapeziumAdjustmentDetails") is not None else None
        })
        return _obj


